### ISSUE TITLE
Broken Android mame .251 games

### ISSUE THREAD

**Issue by 71knight** [libretro/mame#347] opened 2023-04-01 04:25 UTC
Virtua racing-tracks are missing.
Donkey Kong Jr.- crashes randomly while playing.
Star wars arcade Sega model 1- ship shadows are backwards over death star.
Prop cycle- corrupted graphics then crashes.
Time crisis- doesn't get past startup ROM check.
Numan Athletics- blank screen at start.
Soul edge-doesn't detect on screen controls.
Soul Calibur-slows down randomly.

All games tested using opengl backend on Android 11.

**Comment by nemo93** [comment] 2023-07-29 10:30
@71knight hello! This is duplicate of #253. You might consider closing it to focus our effort onto that one please. I've tested the following on **.256**:

* Donkey Kong Jr. : works / no crash after several tries and playthroughs of ~10mn
*  Numan Athletics: black screen (known issue with the driver - #422)
* [Prop Cycle](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=propcycl): currently noted as having "imperfect graphic"
* [Star wars Arcade](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=swa): currently noted as having "imperfect graphic"
* Time crisis: stuck on initial ROM check (#425)
* Virtua racing: tracks are missing (works fine on MAMEUI/Windows)

Tested on: Raspberry Pi4 on a vanilla Retropie (4.8.4). Kernel `5.10.103-v7l+`, 32-bit Raspberry OS in `fKMS` mode. Retroarch is `1.15.0` and the MAME core is `.257`.

**Comment by nemo93** [comment] 2023-08-16 09:46
Most likely the fix is to add the `-fsigned-char` flag as well. [Thread](https://retropie.org.uk/forum/post/290184) on the Retropie's forum for reference which also contains an updated binary for that device.

Thanks a lot @sonninnos @grant2258!

I recommend to close that ticket off.

**Closed as completed** 2023-08-16 11:24 UTC
