### ISSUE TITLE
watchdog reset loop with primal rage 2

### ISSUE THREAD

**Issue by Nit3H8wk** [libretro/mame#93] opened 2019-02-20 01:03 UTC
Getting watchdog reset loop with primal rage 2. The standalone mame 0.206 works fine the game boots up and is playable. When libretro mame was on 0.205 the game also worked fine.

**Comment by Nit3H8wk** [comment] 2019-02-20 01:31
![mame](https://user-images.githubusercontent.com/47800266/53059572-4d149500-3485-11e9-9a16-e95431bc25ca.jpg)

**Comment by Nit3H8wk** [comment] 2019-02-20 01:39
Standalone mame 0.206 
![mame 1](https://user-images.githubusercontent.com/47800266/53059859-6ec24c00-3486-11e9-8aa7-660dd83eee6f.jpg)

**Comment by r-type** [comment] 2019-03-13 20:36
hard time to debug this , but no result for now. 

the only change i see that can lead to this watchdog reset is here
https://github.com/libretro/mame/commit/b0b843c089d47535e1d16f1d8e5318342d50f9d5#diff-a23acd3824845a29942af9bce2456d18

**Comment by r-type** [comment] 2019-03-22 11:19
Im trying to use mame debuger to find the root cause but i'm not so familiar with it.
![diff -debug-190322-120854](https://user-images.githubusercontent.com/3614417/54819609-b7933d80-4c9c-11e9-9fe3-b1ad7f7e5d91.png)

**Comment by Nit3H8wk** [comment] 2019-03-25 10:46
Thank you for taking the time to troubleshoot the issue. Not a huge deal I just prefer to use retroarch mame over standalone. I will keep checking back whenever this thread is updated.

**Comment by tcamargo** [comment] 2020-07-06 01:15
Closing old issues. Please reopen if it is still relevant.

**Comment by Nit3H8wk** [comment] 2020-07-06 04:05
https://www.youtube.com/watch?v=brInYEKhFkw&feature=youtu.be
OBS capture of what happens when I load the game. Stand alone mame still seems to work.

**Comment by tcamargo** [comment] 2020-08-12 20:02
Just tested with macOS standalone mame and got in the WatchDog RESET loop.

**Comment by tcamargo** [comment] 2020-08-12 20:19
Game marked as not working upstream with the mentioned error.

https://github.com/mamedev/mame/blob/9d00d87dac0d4f606268f3eb43335eb81a58cad1/src/mame/drivers/zn.cpp#L5263

Nothing much I can do.

**Closed as completed** 2020-08-12 20:20 UTC
Labels: bug, invalid
