### ISSUE TITLE
[Windows x64] Core crashes and doesn't load any game

### ISSUE THREAD

**Issue by Immersion95** [libretro/mame#228] opened 2021-01-29 18:32 UTC
The latest build doesn't work at all. Tried with latest RA nightlies and everything to default

**Comment by sanchezmike01** [comment] 2021-01-29 18:47
Are the latest cores from a specific site or downloaded from the online updater?

**Comment by Immersion95** [comment] 2021-01-29 18:48
> Are the latest cores from a specific site or downloaded from the online updater?

Online updater

**Comment by tcamargo** [comment] 2021-01-30 09:42
Dupe of https://github.com/libretro/mame/issues/229.

**Closed as completed by tcamargo** 2021-01-30 09:42 UTC
